### ISSUE TITLE
The system accepts id, email address, username and password, created at, updated at.

### ISSUE THREAD

**Issue by annagabriel-hash** [lea927/drop-that-beat#3]
### Tasks
- [x] Install devise gem
- [x] Specify user model
- [x] Create user model
