### ISSUE TITLE
Given that I'm a registered user who is logged it, when I go to the edit game room page, click remove track, the system will remove the tracks from the room.

### ISSUE THREAD

**Issue by annagabriel-hash** [lea927/drop-that-beat#54]
### Tasks

- [ ] Add destroy action to tracks controller which will delete the tracks from the room
- [ ] Update rooms edit page to submit ajax request of deleting tracks from room
- [ ] Add js to remove tracks from the list of tracks in the room
