### ISSUE TITLE
Given that search tracked is already added in the rooms, when I go to the edit game room page, enter a track and click search and click add track, the list of tracks in the room should not change

### ISSUE THREAD

**Issue by annagabriel-hash** [lea927/drop-that-beat#59]
### Tasks
- [ ] Specify that when the track is added twice an error should be raised
```ruby
expect { room.tracks.push(track) }.to raise_error(ActiveRecord::RecordInvalid)
```
- [ ] Update room track model to validate that tracks and room should be unique
```ruby
class RoomTrack < ApplicationRecord
  validates :track, uniqueness: { scope: :room,
    message: 'should only assign once' }
 end
```
- [ ] Update db file to add index to track model
```ruby
add_index :room_tracks, [:track_id, :room_id], unique: true
```
