### ISSUE TITLE
Given that I'm logged in, when I join the game, the system plays the tracks.

### ISSUE THREAD

**Issue by annagabriel-hash** [lea927/drop-that-beat#66]
## Tasks
- [X] Create js file
- [X] Create playlist class 
### Properties
- [X] Add tracks attribute array which contain all tracks
- [X] Add track number to check the currently playing track
- [x] Add isPlaying boolean to check if the playlist is currently playing
### Methods
- [X] Add function to setup the tracks and create Audio object per track url
- [X] Add function to play the playlist
- [X] Add function to pause the playlist
- [x] Add function to end the playlist
- [X] Add function play next track
- [x] Add function to set track number
