### ISSUE TITLE
When the player clicks a music title button, the system posts the selected track name, user id, adam id and track name to determine if the answer is correct

### ISSUE THREAD

**Issue by lea927** [lea927/drop-that-beat#67]
### Tasks
- [x] Add specs to specify when user posted a correct answer
- [x] Update the routes to include the endpoint to post the answer selected
- [x] Update the room controller `answer` action to post the answer selected and add points to user if answer is true
- [x] Add specs to check response from posting of action
- [x] Update the room controller `answer` action to return json true if the answer is corrected; otherwise return false.
- [x] Add specs to specify when user posted an incorrect answer
- [x] Specify that response body should be false when user posted an incorrect answer
- [X] Specify that user points does not changed when user posted invalid attributes
- [x] Update `answer` action to return function when attributes are invalid
- [x] Create a async js function to post the answer selected
