### ISSUE TITLE
As a Player, when I start the game, I want to see the duration of the music to know how long I can decide the correct answer

### ISSUE THREAD

**Issue by lea927** [lea927/drop-that-beat#68]
### User Story
As a Player, when I start the game, I want to see the duration of the music to know how long I can decide the correct answer
### Acceptance Criteria
- [ ] When the player clicks the start game and starts the music, the system consistently displays the duration (in seconds) of the song.
- [ ] The system displays a progress bar to show the duration of the song
- [ ] When the player has answered the question, the system displays the duration of the currently playing song.
### Task 
- [ ] The duration from the playlist class should be passed into a loader/progress bar
